// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkYp3-p7bNlr0Ml_za323uClHaKKnUcFo',
    appId: '1:381234441271:web:0b18bfe44a132492c523b2',
    messagingSenderId: '381234441271',
    projectId: 'antap-b365b',
    authDomain: 'antap-b365b.firebaseapp.com',
    storageBucket: 'antap-b365b.appspot.com',
    measurementId: 'G-39VWM41J30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUK6zO7_Y_EuegxtSuk4KWbGSatGWH0Nw',
    appId: '1:381234441271:android:e72d2fc9447f260cc523b2',
    messagingSenderId: '381234441271',
    projectId: 'antap-b365b',
    storageBucket: 'antap-b365b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN0622xpTnb2MJ5v6rARV4-mKmzn1zkqg',
    appId: '1:381234441271:ios:d5619324d03e013bc523b2',
    messagingSenderId: '381234441271',
    projectId: 'antap-b365b',
    storageBucket: 'antap-b365b.appspot.com',
    iosClientId: '381234441271-4o0iit69qph4ioojckkfvgpk8fg98vs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.antap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN0622xpTnb2MJ5v6rARV4-mKmzn1zkqg',
    appId: '1:381234441271:ios:bd9ef9dc41980ea4c523b2',
    messagingSenderId: '381234441271',
    projectId: 'antap-b365b',
    storageBucket: 'antap-b365b.appspot.com',
    iosClientId: '381234441271-1iie41khm8eaeilaedgi9ivslqqkkqq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.antap.RunnerTests',
  );
}
