// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIu3CWvQ9eNujSQ63uxd2lXWgyErrVRM4',
    appId: '1:16468586993:web:3e3b118b6649713c245450',
    messagingSenderId: '16468586993',
    projectId: 'antap-ba5f2',
    authDomain: 'antap-ba5f2.firebaseapp.com',
    storageBucket: 'antap-ba5f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo_4y_75LXXxCo3FGdi8zgwflbw6_BIe0',
    appId: '1:16468586993:android:fa18372726a0bae0245450',
    messagingSenderId: '16468586993',
    projectId: 'antap-ba5f2',
    storageBucket: 'antap-ba5f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnbSSneHATdkWHSaLI_Xlt2UOkypd5Hw',
    appId: '1:16468586993:ios:86f54bf4afa8ca4a245450',
    messagingSenderId: '16468586993',
    projectId: 'antap-ba5f2',
    storageBucket: 'antap-ba5f2.appspot.com',
    iosClientId: '16468586993-db22o7k3k0svehhklgq1rcas42fe6m1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.antap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWnbSSneHATdkWHSaLI_Xlt2UOkypd5Hw',
    appId: '1:16468586993:ios:53627bb1c86d05a3245450',
    messagingSenderId: '16468586993',
    projectId: 'antap-ba5f2',
    storageBucket: 'antap-ba5f2.appspot.com',
    iosClientId: '16468586993-punaujqqcc8d0avtvt20jgkaenhkcf3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.antap.RunnerTests',
  );
}
